name: Test Lowest Number
on: [push]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test 1
        run: |
          python find_lowest_number.py test_data/test1_input.txt test1_output.txt
          diff test1_output.txt test_data/test1_expected.txt

      - name: Test 2
        run: |
          python find_lowest_number.py test_data/test2_input.txt test2_output.txt
          diff test2_output.txt test_data/test2_expected.txt

      - name: Test 3
        run: |
          python find_lowest_number.py test_data/test3_input.txt test3_output.txt
          diff test3_output.txt test_data/test3_expected.txt
